title: Seika Hirori's homepage

description: Welcome! Follow my programming journey as I learn how to utilize all new tools and concepts :3

# theme: minima
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one


# exclude: [_Docs, _Drafts,]

collections:
  projects:
    output: true
  unique_pages:
    output: true

defaults:
  - scope:
      path: ""
      type: "unique_pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"