remote_theme: pages-themes/time-machine@v0.2.0

title: Seika Hirori's homepage

description: Welcome to my site! Follow me as I progress through my programming journey :3

plugins:
- jekyll-remote-theme 

# exclude: [_Docs, _Drafts,]

collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"