title: Seika Hirori

description: Welcome! Follow my programming journey as I learn how to utilize all new tools and concepts :3

# theme: minima
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

excerpt_separator: <!--more--> # Need to place "<!--more-->" into posts!

default_empty: '໒(⊙ᴗ⊙)७✎▤'

# exclude: [_Docs, _Drafts,]

collections:
  projects:
    output: true
  subpages:
    output: true
  unique_pages:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      # category: "ALL"
  - scope:
      path: "_posts/programming"
      type: "posts"
    values:
      layout: "post_programming"
      category: "Programming"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "subpages"
    values:
      layout: "default"  
  - scope:
      path: ""
      type: "unique_pages"
    values:
      layout: "default"